apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-kubernetes-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ivona13/diy-kubernetes-examples.git'
    path: deploy-kubernetes-helm-chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-nginx.yaml
      parameters:
      - name: "AdminPassword"
        value: "admin"
      - name: "testtest"
        value: ""
      - name: "oidc.enabled"
        value: "false"
      - name: "postgresql.postgresqlPassword"
        value: "postgres"
      - name: "RepositoryKeystore"
        value: "zs7OzgAAAAIAAAABAAAAAwAWZGVwbG95aXQtcGFzc3N3b3JkLWtleQAAAX5y0QJsrO0ABXNyADNjb20uc3VuLmNyeXB0by5wcm92aWRlci5TZWFsZWRPYmplY3RGb3JLZXlQcm90ZWN0b3LNV8pZ5zC7UwIAAHhyABlqYXZheC5jcnlwdG8uU2VhbGVkT2JqZWN0PjY9psO3VHACAARbAA1lbmNvZGVkUGFyYW1zdAACW0JbABBlbmNyeXB0ZWRDb250ZW50cQB+AAJMAAlwYXJhbXNBbGd0ABJMamF2YS9sYW5nL1N0cmluZztMAAdzZWFsQWxncQB+AAN4cHVyAAJbQqzzF/gGCFTgAgAAeHAAAAARMA8ECDx5tHUJQWN8AgMDDUB1cQB+AAUAAACgC120zoQkVEdn0BDGc+Gv8124in4gXHFd+licENOWjxCJNHD+Rd2bFsS8ZP/zAbhSmL12iQF0ZMzkDK6ZF4hYc+3MO4N0KAKsWRx1VYQJxzWuZA9VMReB4BlKQ6INHqNr9Lb7ovSkPAhXwXywlS38bRK/u7u5LaiXTf/Zwl9AgLgYrDpcRXHKyg4T7qkiWimh8M/WMbuZbl/WIvRO4a7D2XQAFlBCRVdpdGhNRDVBbmRUcmlwbGVERVN0ABZQQkVXaXRoTUQ1QW5kVHJpcGxlREVT2mztslTqsBUgDMY7Vp/Y7wuW4K0="
      - name: "xldLicense"
        value: "LS0tIExpY2Vuc2UgLS0tCkxpY2Vuc2UgdmVyc2lvbjogMwpQcm9kdWN0OiBYTCBEZXBsb3kKTGljZW5zZWQgdG86IFhlYmlhTGFicyAtIFRlc3RpbmcgT25seSEKQ29udGFjdDogSnl0aG9uIFRlc3QKRXhwaXJlcyBhZnRlcjogMjAzNy0wMS0wMQpNYXhpbXVtIG51bWJlciBvZiB1c2VyczogMgpMaWNlbnNlZCBudW1iZXIgb2YgQ0lzOiB1ZG0uQXBwbGljYXRpb249MTAwMDAKTGljZW5zZWQgcGx1Z2luOiB0b21jYXQtcGx1Z2luCkxpY2Vuc2VkIHBsdWdpbjogd2FzLXBsdWdpbgpMaWNlbnNlZCBwbHVnaW46IGlpcy1wbHVnaW4KU3VwcG9ydCBwb2xpY3k6IDI0eDcKRWRpdGlvbjogRW50ZXJwcmlzZQotLS0gU2lnbmF0dXJlIChTSEExd2l0aERTQSkgLS0tCjMwMmMwMjE0NjRlMTNmNzc2NmEyZWZmYTRlZDUxNzQyNjhjMzgyODk2NzAzZjI4NDAyMTQxMTgxMTAzZjQ4ZWFmYjA5NThhMjY3MWNmZWMxCjViNWYzOWQ3NTZmYgotLS0gRW5kIG9mIFNpZ25hdHVyZSAtLS0="
      - name: "Persistence.StorageClass"
        value: "standard"
      - name: "postgresql.persistence.storageClass"
        value: "standard"
      - name: "rabbitmq.persistence.storageClass"
        value: "standard"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deploy
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
